blueprint:
  name: Ceiling light with night mode - toggle & long-press override
  description: >
    Short press toggles normal or night light depending on night_sensor state.
    Long press forces the opposite light on.

  domain: automation

  input:
    button_device:
      name: Control button
      description: The button device used to control the ceiling light
      selector:
        device: {}

    normal_light:
      name: Normal light entity
      selector:
        entity:
          domain:
            - light
            - switch

    night_light:
      name: Nightlight entity
      selector:
        entity:
          domain:
            - light
            - switch

    night_sensor:
      name: Nightlight status sensor
      selector:
        entity:
          domain: binary_sensor

trigger:
  # Short press
  - platform: device
    device_id: !input button_device
    domain: zha
    type: remote_button_short_press
    subtype: remote_button_short_press
    id: short_press

  # Long press
  - platform: device
    device_id: !input button_device
    domain: zha
    type: remote_button_double_press
    subtype: remote_button_double_press
    id: long_press

condition: []

action:
  - choose:
      # ----------------------
      # Short press behavior
      # ----------------------
      - conditions:
          - condition: trigger
            id: short_press
        sequence:
          - choose:
              # Night sensor OFF → toggle NORMAL light
              - conditions:
                  - condition: state
                    entity_id: !input night_sensor
                    state: "off"
                sequence:
                  - service: homeassistant.toggle
                    target:
                      entity_id: !input normal_light

              # Night sensor ON → toggle NIGHT light
              - conditions:
                  - condition: state
                    entity_id: !input night_sensor
                    state: "on"
                sequence:
                  - service: homeassistant.toggle
                    target:
                      entity_id: !input night_light

      # ----------------------
      # Long press behavior
      # ----------------------
      - conditions:
          - condition: trigger
            id: long_press
        sequence:
          - choose:
              # Night sensor OFF → turn NIGHT light ON
              - conditions:
                  - condition: state
                    entity_id: !input night_sensor
                    state: "off"
                sequence:
                  - service: homeassistant.turn_on
                    target:
                      entity_id: !input night_light

              # Night sensor ON → turn NORMAL light ON
              - conditions:
                  - condition: state
                    entity_id: !input night_sensor
                    state: "on"
                sequence:
                  - service: homeassistant.turn_on
                    target:
                      entity_id: !input normal_light

mode: restart